import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:audioplayers/audioplayers.dart';
import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:path_provider/path_provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../utils/tanglish.dart';
// Prefixed too: this class has a setting named transliterateTanglish that
// would otherwise shadow the function.
import '../utils/tanglish.dart' as tanglish show transliterateTanglish;
import 'gemini_speech.dart';

/// The four selectable characters.
///
/// The platform engine only exposes real voices per locale, and none of them is
/// a child or a cartoon — so [child] and [comic] are built by shifting pitch and
/// rate on top of the best available base voice. [male] and [female] pick an
/// actual gendered engine voice when the device has one, and fall back to a
/// pitch offset when it doesn't.
enum VoiceCharacter { male, female, child, comic }

extension VoiceCharacterInfo on VoiceCharacter {
  String get label => switch (this) {
        VoiceCharacter.male => 'Male',
        VoiceCharacter.female => 'Female',
        VoiceCharacter.child => 'Child',
        VoiceCharacter.comic => 'Comic',
      };

  String get description => switch (this) {
        VoiceCharacter.male => 'Deeper adult voice',
        VoiceCharacter.female => 'Higher adult voice',
        VoiceCharacter.child => 'Young, bright and quick',
        VoiceCharacter.comic => 'Exaggerated cartoon voice',
      };

  /// Pitch multiplier applied on top of the base voice.
  double get pitch => switch (this) {
        VoiceCharacter.male => 0.88,
        VoiceCharacter.female => 1.08,
        VoiceCharacter.child => 1.55,
        VoiceCharacter.comic => 1.95,
      };

  /// Rate multiplier — children and cartoons talk faster.
  double get rateFactor => switch (this) {
        VoiceCharacter.male => 1.0,
        VoiceCharacter.female => 1.0,
        VoiceCharacter.child => 1.08,
        VoiceCharacter.comic => 1.2,
      };

  /// Which engine voice gender to prefer as the base.
  bool get prefersFemaleBase => this != VoiceCharacter.male;

  /// Gemini prebuilt voice for this character.
  ///
  /// Female was Kore, which measured a median pitch of ~190 Hz reading Tamil
  /// — female, but low enough to sound masculine at times. Sulafat measured
  /// ~229 Hz, comfortably and consistently feminine.
  String get geminiVoice => switch (this) {
        VoiceCharacter.male => 'Charon',
        VoiceCharacter.female => 'Sulafat',
        VoiceCharacter.child => 'Leda',
        VoiceCharacter.comic => 'Puck',
      };

  /// What the character sounds like, as Gemini's natural-language style
  /// direction. This is what makes child and comic sound like characters
  /// rather than a normal voice at a higher pitch.
  String get geminiStyle => switch (this) {
        VoiceCharacter.male => 'a calm, friendly adult man',
        VoiceCharacter.female =>
          'a sweet, soft-spoken young woman with a gentle, warm and feminine voice',
        VoiceCharacter.child =>
          'a cheerful young child, light, bright and playful',
        VoiceCharacter.comic =>
          'an over-the-top cartoon character, funny, exaggerated and full of energy',
      };
}

const _kCharacterKey = 'tts_character';
const _kRateKey = 'tts_rate';
const _kAutoReadKey = 'tts_auto_read';
const _kTranslitKey = 'tts_transliterate_tanglish';
const _kUseCloudKey = 'tts_use_cloud';

/// Reads chat messages aloud in English, Tamil and Tanglish.
///
/// Two engines:
///
/// * **Gemini** (default) — free-tier Gemini converts Tanglish to Tamil script
///   and speaks it ([GeminiSpeech]). This is the only way to read Tamil on a
///   phone whose TTS engine has no Tamil voice, which is common.
/// * **Device** — the platform engine, used when the user picks it, or as an
///   automatic fallback when Gemini can't be used (offline, no key in this
///   build, or the free daily limit is used up).
///
/// A single instance owns playback, because two screens each driving their
/// own player would talk over each other. Listen to it to render per-message
/// loading and playing state.
class TtsService extends ChangeNotifier {
  TtsService._();
  static final TtsService instance = TtsService._();

  final FlutterTts _tts = FlutterTts();
  final AudioPlayer _player = AudioPlayer();
  Completer<void>? _clipDone;

  bool _ready = false;
  bool _initFailed = false;

  // ── Settings ───────────────────────────────────────────────────────────────
  VoiceCharacter _character = VoiceCharacter.female;
  double _rate = 0.5; // engine-normalised 0..1
  bool _autoRead = false;
  bool _transliterateTanglish = true;
  bool _useCloud = true;

  /// Whether audio is generated by Gemini rather than the device. Requires a
  /// build with a key; see [GeminiSpeech.isConfigured].
  bool get useCloud => _useCloud && GeminiSpeech.isConfigured;

  /// Whether this build can use Gemini at all.
  bool get cloudAvailable => GeminiSpeech.isConfigured;

  /// True while every Gemini voice model is resting after being overloaded
  /// or hitting its free limit; new messages use the phone voice meanwhile.
  bool get quotaExhausted => GeminiSpeech.allResting(GeminiSpeech.voiceModels);

  /// Why the last message fell back to the phone voice, for the settings
  /// screen. Null once Gemini reads a message again.
  String? _lastFallbackReason;
  String? get lastFallbackReason => _lastFallbackReason;

  /// Called when a message is read with the phone voice instead of Gemini, so
  /// the app can say so — otherwise the voice change just sounds like a bug.
  void Function(String reason)? onFallback;

  VoiceCharacter get character => _character;
  double get rate => _rate;
  bool get autoRead => _autoRead;
  bool get transliterateTanglish => _transliterateTanglish;
  bool get initFailed => _initFailed;

  // ── Playback state ─────────────────────────────────────────────────────────
  /// Id of the message currently being read, or null when idle. Bubbles use
  /// this to show a stop button instead of a play button.
  String? _speakingId;
  String? get speakingId => _speakingId;
  bool isSpeaking(String messageId) => _speakingId == messageId;

  /// Id of the message whose cloud audio is being fetched. The fetch takes a
  /// moment, and without a visible state a tap looks like it did nothing.
  String? _loadingId;
  bool isLoading(String messageId) => _loadingId == messageId;

  /// Incremented on every stop/new request so an in-flight run loop can tell
  /// that it has been superseded and bail out instead of continuing to speak.
  int _generation = 0;

  // ── Voice inventory ────────────────────────────────────────────────────────
  bool _tamilAvailable = false;
  bool get tamilAvailable => _tamilAvailable;
  List<Map<String, String>> _voices = const [];

  /// Locales we ask the engine for. English falls back automatically if the
  /// Indian English voice is missing.
  static const _googleEngine = 'com.google.android.tts';
  static const _englishLocales = ['en-IN', 'en-GB', 'en-US'];
  static const _tamilLocales = ['ta-IN', 'ta-LK', 'ta'];

  String _englishLocale = 'en-IN';
  String _tamilLocale = 'ta-IN';

  Future<void> init() async {
    if (_ready) return;
    try {
      final prefs = await SharedPreferences.getInstance();
      final idx = prefs.getInt(_kCharacterKey);
      if (idx != null && idx >= 0 && idx < VoiceCharacter.values.length) {
        _character = VoiceCharacter.values[idx];
      }
      _rate = prefs.getDouble(_kRateKey) ?? 0.5;
      _autoRead = prefs.getBool(_kAutoReadKey) ?? false;
      _transliterateTanglish = prefs.getBool(_kTranslitKey) ?? true;
      _useCloud = prefs.getBool(_kUseCloudKey) ?? true;

      // Sequential playback depends on speak() completing before it returns;
      // without this the engine fires and forgets and multi-language messages
      // collapse into one garbled utterance.
      await _tts.awaitSpeakCompletion(true);

      // Many phones — Samsung especially — default to a speech engine with no
      // Tamil voice even when Google's engine, which has one, is installed.
      // Prefer Google's so the offline fallback can speak Tamil wherever
      // that's possible.
      if (Platform.isAndroid) {
        try {
          final engines = await _tts.getEngines;
          if (engines is List && engines.contains(_googleEngine)) {
            await _tts.setEngine(_googleEngine);
          }
        } catch (_) {}
      }

      await _loadInventory();

      _tts.setCompletionHandler(_onEngineIdle);
      _tts.setCancelHandler(_onEngineIdle);
      _tts.setErrorHandler((_) => _onEngineIdle());

      _ready = true;
    } catch (_) {
      _initFailed = true;
    }
    notifyListeners();
  }

  Future<void> _loadInventory() async {
    // Pick the best available locale for each language.
    for (final l in _englishLocales) {
      if (await _isAvailable(l)) {
        _englishLocale = l;
        break;
      }
    }
    _tamilAvailable = false;
    for (final l in _tamilLocales) {
      if (await _isAvailable(l)) {
        _tamilLocale = l;
        _tamilAvailable = true;
        break;
      }
    }

    try {
      final raw = await _tts.getVoices;
      if (raw is List) {
        _voices = raw
            .whereType<Map>()
            .map((v) => {
                  'name': '${v['name'] ?? ''}',
                  'locale': '${v['locale'] ?? ''}',
                  'gender': '${v['gender'] ?? ''}',
                })
            .where((v) => v['name']!.isNotEmpty)
            .toList();
      }
    } catch (_) {
      _voices = const [];
    }
  }

  Future<bool> _isAvailable(String locale) async {
    try {
      final r = await _tts.isLanguageAvailable(locale);
      return r == true;
    } catch (_) {
      return false;
    }
  }

  /// Re-checks the engine — call after the user installs a missing voice.
  Future<void> refreshVoices() async {
    await _loadInventory();
    notifyListeners();
  }

  // ── Settings mutators ──────────────────────────────────────────────────────

  Future<void> setCharacter(VoiceCharacter c) async {
    if (_character == c) return;
    _character = c;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setInt(_kCharacterKey, c.index);
  }

  Future<void> setRate(double r) async {
    _rate = r.clamp(0.2, 1.0);
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setDouble(_kRateKey, _rate);
  }

  Future<void> setAutoRead(bool v) async {
    if (_autoRead == v) return;
    _autoRead = v;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_kAutoReadKey, v);
  }

  Future<void> setUseCloud(bool v) async {
    if (_useCloud == v) return;
    _useCloud = v;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_kUseCloudKey, v);
  }

  Future<void> setTransliterateTanglish(bool v) async {
    if (_transliterateTanglish == v) return;
    _transliterateTanglish = v;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_kTranslitKey, v);
  }

  // ── Speaking ───────────────────────────────────────────────────────────────

  static const _previewId = '__preview__';

  /// Reads [text] aloud, tagged with [messageId] so the UI can show progress.
  ///
  /// Tapping the same message again stops it; tapping a different one
  /// interrupts the first. Returns without doing anything if there is nothing
  /// speakable in [text].
  ///
  /// [phoneVoiceOnly] skips Gemini — used for automatic reading, which would
  /// otherwise spend the small free daily allowance before anything is tapped.
  Future<void> speak(String messageId, String text,
      {bool phoneVoiceOnly = false}) async {
    await init();
    if (_speakingId == messageId || _loadingId == messageId) {
      await stop();
      return;
    }
    if (!isSpeakable(text)) return;

    await stop();
    final gen = ++_generation;

    if (!phoneVoiceOnly && useCloud && !quotaExhausted) {
      final handled = await _speakCloud(gen, messageId, text, _character);
      if (handled || gen != _generation) return;
      // Cloud unavailable — fall through so the tap still produces speech.
    }
    await _speakDevice(gen, messageId, text, _character);
  }

  /// Speaks a short sample so the user can audition a character in settings.
  Future<void> preview(VoiceCharacter c) async {
    await init();
    await stop();
    final gen = ++_generation;
    const sample = 'வணக்கம்! Hello, this is how your messages will sound.';
    if (useCloud && !quotaExhausted) {
      final handled = await _speakCloud(gen, _previewId, sample, c);
      if (handled || gen != _generation) return;
    }
    await _speakDevice(gen, _previewId, sample, c);
  }

  Future<void> stop() async {
    _generation++;
    if (_speakingId != null || _loadingId != null) {
      _speakingId = null;
      _loadingId = null;
      notifyListeners();
    }
    final done = _clipDone;
    if (done != null && !done.isCompleted) done.complete();
    try {
      await _player.stop();
    } catch (_) {}
    try {
      await _tts.stop();
    } catch (_) {}
  }

  void _onEngineIdle() {
    if (_speakingId != null && _loadingId == null) {
      _speakingId = null;
      notifyListeners();
    }
  }

  // ── Gemini engine ──────────────────────────────────────────────────────────

  /// Plays [text] through Gemini. Returns false only when Gemini could not
  /// produce audio, so the caller can fall back to the device voice.
  Future<bool> _speakCloud(
      int gen, String id, String text, VoiceCharacter c) async {
    _loadingId = id;
    notifyListeners();

    File clip;
    try {
      clip = await _geminiClip(text, c);
    } catch (e) {
      debugPrint('Gemini speech unavailable, using device voice: $e');
      final reason = e is GeminiQuotaException
          ? (e.daily
              ? "Today's free Gemini limit is used up"
              : 'Gemini free limit reached for this minute')
          : 'Gemini is busy right now';
      _lastFallbackReason = reason;
      if (gen == _generation) {
        _loadingId = null;
        notifyListeners();
        onFallback?.call('$reason — read with the phone voice.');
      }
      return false;
    }
    if (gen != _generation) return true; // stopped while loading

    _loadingId = null;
    _speakingId = id;
    _lastFallbackReason = null;
    notifyListeners();
    try {
      await _playClip(clip);
    } catch (_) {}
    if (gen == _generation) {
      _speakingId = null;
      notifyListeners();
    }
    return true;
  }

  /// Gemini's spoken style direction for [c] at the current speed.
  String _styleFor(VoiceCharacter c) {
    final pace = _rate < 0.4
        ? ' Speak slowly.'
        : _rate > 0.65
            ? ' Speak quickly.'
            : '';
    return 'Read this as ${c.geminiStyle}, speaking naturally like a native '
        'Tamil speaker from Tamil Nadu, in one consistent voice from start to '
        'finish. Read any English with a natural Indian accent. Never read '
        'punctuation aloud. Where you see "...", let the word just before it '
        'trail off and stretch out slowly, then pause.$pace';
  }

  /// The audio for [text], from the on-device cache or from Gemini.
  ///
  /// The language is decided on the phone first, for the whole message:
  /// plain English skips the rewrite (one request instead of two, and no risk
  /// of the model turning English into Tamil script), and a message that is
  /// Tamil anywhere is rewritten entirely into Tamil so one voice reads it.
  ///
  /// Both steps are cached, so replaying a message is instant and uses none
  /// of the free allowance. If the rewrite is unavailable, the phone converts
  /// the Tanglish itself and the Gemini voice still reads it.
  Future<File> _geminiClip(String text, VoiceCharacter c) async {
    final root = (await getTemporaryDirectory()).path;
    final planDir = Directory('$root/tts_plans');
    final audioDir = Directory('$root/tts_audio');

    final prepared = prepareForSpeech(text);
    if (prepared.isEmpty) throw const GeminiException('nothing to read');
    final language = classifyMessage(prepared);

    var spoken = prepared;
    if (GeminiSpeech.needsPlan(prepared) &&
        language != MessageLanguage.english) {
      final planFile = File('${planDir.path}/${_hash('p2|$prepared')}.txt');
      if (await planFile.exists()) {
        spoken = await planFile.readAsString();
      } else {
        try {
          spoken = await GeminiSpeech.planSpeech(
            prepared,
            knownTamil: language == MessageLanguage.tamil,
          );
          await planDir.create(recursive: true);
          await planFile.writeAsString(spoken, flush: true);
        } on GeminiException {
          // Not cached, so a later play gets the better Gemini rewrite.
          spoken = language == MessageLanguage.tamil
              ? tanglish.transliterateTanglish(prepared)
              : prepared;
        }
      }
    }

    final style = _styleFor(c);
    final audioFile = File(
        '${audioDir.path}/${_hash('a2|${c.geminiVoice}|$style|$spoken')}.wav');
    if (await audioFile.exists() && await audioFile.length() > 44) {
      return audioFile;
    }
    final bytes = await GeminiSpeech.synthesize(
      spoken,
      voice: c.geminiVoice,
      style: style,
    );
    await audioDir.create(recursive: true);
    // Write to a temp name first so an interrupted write is never served.
    final partial = File('${audioFile.path}.part');
    await partial.writeAsBytes(bytes, flush: true);
    await partial.rename(audioFile.path);
    return audioFile;
  }

  static String _hash(String s) => sha256.convert(utf8.encode(s)).toString();

  /// Plays one clip and completes when it ends or [stop] is called.
  Future<void> _playClip(File clip) async {
    final done = Completer<void>();
    _clipDone = done;
    final sub = _player.onPlayerComplete.listen((_) {
      if (!done.isCompleted) done.complete();
    });
    try {
      await _player.play(DeviceFileSource(clip.path));
      await done.future;
    } finally {
      await sub.cancel();
      if (identical(_clipDone, done)) _clipDone = null;
    }
  }

  // ── Device engine ──────────────────────────────────────────────────────────

  Future<void> _speakDevice(
      int gen, String id, String text, VoiceCharacter c) async {
    final runs = planSpeech(text, transliterate: _transliterateTanglish);
    if (runs.isEmpty) return;
    _speakingId = id;
    notifyListeners();

    for (final run in runs) {
      if (gen != _generation) return; // superseded by a newer request
      // Without a Tamil voice the run goes to the English engine, which can
      // approximate Latin-letter Tanglish but cannot pronounce Tamil script at
      // all — so give it what the user typed, and skip what it can't read.
      final say = run.isTamil && !_tamilAvailable ? run.original : run.text;
      if (!_tamilAvailable && hasTamilScript(say)) continue;
      try {
        await _applyVoice(tamil: run.isTamil, override: c);
        await _tts.speak(say);
      } catch (_) {
        break;
      }
    }
    if (gen == _generation) {
      _speakingId = null;
      notifyListeners();
    }
  }

  /// Configures locale, engine voice, pitch and rate for the next utterance.
  Future<void> _applyVoice({
    required bool tamil,
    VoiceCharacter? override,
  }) async {
    final c = override ?? _character;
    // A Tamil run with no Tamil voice installed would be read with English
    // phonetics, which is worse than useless — speak it with the English voice
    // only because there is no alternative, and let the settings screen tell
    // the user how to install the real one.
    final useTamil = tamil && _tamilAvailable;
    final locale = useTamil ? _tamilLocale : _englishLocale;

    try {
      await _tts.setLanguage(locale);
    } catch (_) {}

    final voice = _pickVoice(locale, c.prefersFemaleBase);
    if (voice != null) {
      try {
        await _tts.setVoice(voice);
      } catch (_) {}
    }

    try {
      await _tts.setPitch(c.pitch);
      await _tts.setSpeechRate((_rate * c.rateFactor).clamp(0.1, 1.0));
    } catch (_) {}
  }

  /// Finds an engine voice for [locale], preferring the requested gender.
  ///
  /// Android rarely reports gender, so this also reads the Google voice naming
  /// convention (`...#male_1-local`) and falls back to any voice for the locale.
  Map<String, String>? _pickVoice(String locale, bool preferFemale) {
    if (_voices.isEmpty) return null;
    final lang = locale.split('-').first.toLowerCase();
    final forLocale = _voices
        .where((v) => v['locale']!.toLowerCase().startsWith(lang))
        .toList();
    if (forLocale.isEmpty) return null;

    bool isFemale(Map<String, String> v) {
      final g = v['gender']!.toLowerCase();
      if (g.startsWith('f')) return true;
      if (g.startsWith('m')) return false;
      return v['name']!.toLowerCase().contains('female');
    }

    bool isMale(Map<String, String> v) {
      final g = v['gender']!.toLowerCase();
      if (g.startsWith('m')) return true;
      if (g.startsWith('f')) return false;
      final n = v['name']!.toLowerCase();
      return n.contains('male') && !n.contains('female');
    }

    final wanted =
        forLocale.where(preferFemale ? isFemale : isMale).toList();
    final chosen = wanted.isNotEmpty ? wanted.first : forLocale.first;
    // setVoice only accepts name + locale.
    return {'name': chosen['name']!, 'locale': chosen['locale']!};
  }

  /// Reads an incoming message if the user turned auto-read on.
  ///
  /// Silently does nothing otherwise, so callers can invoke it unconditionally.
  Future<void> maybeAutoRead(String messageId, String text) async {
    await init();
    if (!_autoRead) return;
    // Gemini's free tier allows only ~10 voice requests a day per model, so
    // incoming messages are read with the phone voice; Gemini is kept for
    // the messages you choose to hear.
    await speak(messageId, text, phoneVoiceOnly: true);
  }
}
